### ISSUE TITLE
Project does not compile in JDK 11.0.1 cause of finalize() deprecation

### ISSUE THREAD

**Issue by platgeo** [msiedlarek/winthing#13]
See log:

[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /D:/Users/foo/Documents/GitHub/winthing/src/main/java/com/fatico/winthing/systems/radeon/RadeonService.java:[41,20] finalize() in java.lang.Object has been deprecated
[WARNING] /D:/Users/foo/Documents/GitHub/winthing/src/main/java/com/fatico/winthing/systems/radeon/RadeonService.java:[43,14] finalize() in java.lang.Object has been deprecated
[INFO] 2 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/Users/foo/Documents/GitHub/winthing/src/main/java/com/fatico/winthing/systems/radeon/RadeonService.java: warnings found and -Werror specified
[INFO] 1 error

**Comment by firestrife23** [comment]
Use JDK 8, that's what I did to get it working, I'm afraid this project is not actively developing and may have to look elsewhere, I came here for same reason as you....
